"
" vimrc
"
set nocompatible

" Configure vim(1) to use XDG directories.
if empty($XDG_CONFIG_HOME)
	let $XDG_CONFIG_HOME = $HOME . '/.config'
endif

if empty($XDG_DATA_HOME)
	let $XDG_DATA_HOME = $HOME . '/.local/share'
endif

if empty($XDG_STATE_HOME)
	let $XDG_STATE_HOME = $HOME . '/.local/state'
endif

set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$VIM/vimfiles
set runtimepath+=$VIMRUNTIME
set runtimepath+=$VIM/vimfiles/after
set runtimepath+=$XDG_CONFIG_HOME/vim/after
set packpath^=$XDG_CONFIG_HOME/vim
set packpath+=$VIM/vimfiles
set packpath+=$VIMRUNTIME
set packpath+=$VIM/vimfiles/after
set packpath+=$XDG_CONFIG_HOME/vim/after
set backupdir=$XDG_STATE_HOME/vim/backup
call mkdir(&backupdir, 'p', 0700)
set directory=$XDG_STATE_HOME/vim/swap
call mkdir(&directory, 'p', 0700)
set undodir=$XDG_STATE_HOME/vim/undo
call mkdir(&undodir, 'p', 0700)
set viewdir=$XDG_STATE_HOME/vim/view
call mkdir(&viewdir, 'p', 0700)
set viminfofile=$XDG_STATE_HOME/vim/viminfo

" Enable syntax highlighting.
syntax on

" Enable file type detection.
filetype plugin indent on

" Set up global variables.
let g:netrw_home = $XDG_DATA_HOME . '/vim'
let g:netrw_banner = 0
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_liststyle = 3
let g:is_posix = 1

" Set up editor options.
set encoding=utf-8
set autoindent
set smartindent
set smarttab
set backspace=indent,eol,start
set nowrap
set number
set relativenumber
set colorcolumn=81
set cursorline
set showmode
set ignorecase
set smartcase
set path+=**
set wildmenu
set laststatus=2
set statusline^=%<%f\ %h%w%m%r
set statusline+=%=
set statusline+=%-14.(%l,%c%V%)\ %P
